### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Jobenland/CSV-Graph-Generator#1]
Hiya

Just stopping in to compliment you on the program you've created.   You use techniques I've not seen put together before.  

And thanks for trying out PySimpleGUI and going with it.   You've got a lot of choices and I appreciate you choosing PySimpleGUI for your project.

**Comment by Jobenland** [comment]
Thank You! I appreciate the feedback, I plan to add many more features using the tools you included in PySimpleGUI. Keep checking back to see the new features I've added!

**Comment by MikeTheWatchGuy** [comment]
And great job of putting an image in your readme.  SO many people with cool GUIs are not doing this step which is a shame because they're nice looking GUIs and an image says it all.
